### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by giftedunicorn** [sabinbajracharya/Insta-crawler#2]
Hi I like your project very much and would like to give a shot. 

I did everything as you put in the README and they are all good. But it failed and throw me an error when I run the code. It seams like the response data is in html format instead of json format, and it fails to get id of the user object. How to solve this? Thanks.

**Comment by sabinbajracharya** [comment]
Turns out now Instragram profile URL requires **cookie** and **sessionid** headers as well. 
While visiting instragram profile you can monitor the http request to fetch user profile and copy the cookie and session id
.

**Comment by giftedunicorn** [comment]
Yes, this is what I did. 
I used this API to get user profile https://apinsta.herokuapp.com/u/${USERNAME}. And then add user-agent and cookie (login instagram and copy from your browser) to post request headers. It works.
